name: the_master_holocron
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  share_plus: ^10.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/dogs.jpg
    - assets/images/Characters.jpg
    - assets/images/Creatures.jpg
    - assets/images/Droids.jpg
    - assets/images/Localizations.jpg
    - assets/images/Organizations.jpg
    - assets/images/Species.jpg
    - assets/images/Vehicles.jpg
    - assets/icons/holocron.png
    - assets/icons/JediHolocron.png
    - assets/images/JediHolocronSplash.png


  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
